### ISSUE TITLE
Binance balances not displaying

### ISSUE THREAD

**Issue by RcrossF** [kemargrant/c4d#8]
Balances load without issue on the settings page: https://i.imgur.com/JJRGadl.png but using these settings: https://i.imgur.com/N0BjtNr.png the binance page does not plot any data whatsoever and shows this at the bottom: https://i.imgur.com/VW33k0a.png. The bittrex page plots data and order book fine. Is there a reason this would happen?

**Comment by kemargrant** [comment]
You made an error in setting up your binance pairs. You were very close to setting it up correctly however. Post your binance pairs settings and I will tell you where you went wrong.

**Comment by RcrossF** [comment]
Here are my pairs: 
```
                        "pair1":"ETH_BTC",
                        "pair2":"BNB_BTC",
                        "pair3":"BNB_ETH",
```

**Comment by kemargrant** [comment]
For Binance use lower case and reverse your "fluid" market.
                        "pair1":"eth_btc",
                        "pair2":"btc_bnb",
                        "pair3":"eth_bnb",

**Comment by crypto-maniac** [comment]
hello, i like to know more about the config since i must admit i still did not understand these step

right now per exemple if i want to work with 
(AB step): BTC  =>   BNB
(BC step): BNB  =>  TRX
(CA step): TRX => BTC 

could you please tell me what i should enter into PAIR1 please?

should it be like this ?

> "pair1":"BTC_BNB",
> "pair2":"BNB_TRX",
> "pair3":"TRX_BTC",

is it correct ?

thanks you very much

**Comment by kemargrant** [comment]
You need to use lowercase for Binance, and you need to pay attention to how Binance pairs are defined.

"pair1":"trx_btc",
"pair2":"btc_bnb",
"pair3":"trx_bnb",
